---
engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
    config:
      config: path/to/.eslintrc.js
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- config/
- node_modules/
- test/
